spring:
  datasource:
    url: jdbc:h2:mem:payments;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true
logging:
  level:
    root: INFO
    com.acme.payments: DEBUG
